services:
  db:
    image: mariadb:10.4
    restart: on-failure
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - dbdata:/var/lib/mysql

  wordpress-dev:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-wpdebug-php${PHP_VERSION}
    ports:
      - 8181:80
    restart: on-failure
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: start_with_request=yes client_host=host.docker.internal client_port=8999
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - "./:/var/www/html/wp-content/plugins/ledyer-payments-for-woocommerce"
      - wpdata:/var/www/html

  wordpress-cron:
    depends_on:
      - wordpress-dev
    build:
      context: .
      dockerfile: Dockerfile-cron
    restart: on-failure

  wordpress-cli:
    depends_on:
      - db
      - wordpress-dev
    image: wordpress:cli
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SCRIPT_DEBUG', true );
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --url=http://localhost:8181 --title="Ledyer Payments" --admin_user=admin --admin_password=password --admin_email=info@example.com --path=/var/www/html --skip-email;
      wp rewrite structure /%postname%/;
      wp plugin install wordpress-importer --activate;
      wp plugin install wp-rollback --activate;
      wp plugin install woocommerce --version=8.2.2 --activate;
      wp theme install storefront --activate;
      wp wc tool run install_pages --user=1;
      wp import wp-content/plugins/woocommerce/sample-data/sample_products.xml --authors=create;
      '
    volumes:
      - "./:/var/www/html/wp-content/plugins/ledyer-payments-for-woocommerce"
      - wpdata:/var/www/html

volumes:
  dbdata:
  wpdata:
